use EDUCATION

SELECT TOP 2 * FROM FACTORS
SELECT TOP 2 * FROM PARENTS
SELECT TOP 2 * FROM STUDENTS 

--- JOIN ALL TABLES USING FULL JOIN INTO A NEW TABLE CALLED 'EXAM'

SELECT
STUDENTS.Student_ID, STUDENTS.Gender,STUDENTS.Exam_Score,STUDENTS.Previous_Scores,
PARENTS.Family_Income,PARENTS.Parental_Education_Level,PARENTS.Parental_Involvement,
FACTORS.Access_to_Resources,FACTORS.Attendance,FACTORS.Distance_from_Home,FACTORS.Extracurricular_Activities,
FACTORS.Sleep_Hours,FACTORS.Motivation_Level,
FACTORS.Internet_Access,FACTORS.Tutoring_Sessions,FACTORS.Teacher_Quality,FACTORS.School_Type,FACTORS.Peer_Influence,
FACTORS.Physical_Activity,Learning_Disabilities,FACTORS.Hours_Studied
INTO EXAM 
FROM STUDENTS 
JOIN FACTORS ON STUDENTS.STUDENT_ID = FACTORS.STUDENT_ID 
JOIN PARENTS ON FACTORS.STUDENT_ID = PARENTS.STUDENT_ID

--- VIEW NEW TABLE 
SELECT * FROM EXAM 



--- QUESTION 1: WHAT IS THE AVERAGE EXAM SCORE GROUPED BY HOURS STUDY?  (FROM HIGHEST TO LOWEST) 
SELECT 
CASE 
WHEN Hours_Studied <= 5 THEN '0-5 HOURS' WHEN Hours_Studied <= 10 THEN '6-10 HOURS' WHEN Hours_Studied <= 15 THEN '11-15 HOURS'
WHEN Hours_Studied <= 20 THEN '16-20 HOURS' WHEN Hours_Studied <= 25 THEN '21-25 HOURS' WHEN Hours_Studied <= 30 THEN '26-30 HOURS'
ELSE '30+ HOURS'
END AS STUDY_HOURS_RANGE,
ROUND(AVG(EXAM_SCORE),1) AS AVERAGE_EXAM_SCORE
FROM EXAM 
GROUP BY 
CASE 
WHEN Hours_Studied <= 5 THEN '0-5 HOURS' WHEN Hours_Studied <= 10 THEN '6-10 HOURS' WHEN Hours_Studied <= 15 THEN '11-15 HOURS' 
WHEN Hours_Studied <= 20 THEN '16-20 HOURS' WHEN Hours_Studied <= 25 THEN '21-25 HOURS' WHEN Hours_Studied <= 30 THEN '26-30 HOURS'
ELSE '30+ HOURS'
END
ORDER BY AVERAGE_EXAM_SCORE DESC

SELECT * FROM EXAM 

--- QUESTION 2: HOW DO AVERAGE EXAM SCORES VARY ACROSS DIFFERENT ATTENDANCE LEVELS?
SELECT 
CASE 
WHEN ATTENDANCE <= 20 THEN '0-20' WHEN ATTENDANCE <= 40 THEN '21-40' WHEN ATTENDANCE <= 60 THEN '41-60'
WHEN ATTENDANCE <= 80 THEN '61-80'  ELSE '80+'
END AS ATTENDANCE_RANGE,
ROUND(AVG(EXAM_SCORE),1) AS AVERAGE_EXAM_SCORE
FROM EXAM 
GROUP BY 
CASE 
WHEN ATTENDANCE <= 20 THEN '0-20' WHEN ATTENDANCE <= 40 THEN '21-40' WHEN ATTENDANCE <= 60 THEN '41-60'
WHEN ATTENDANCE <= 80 THEN '61-80'  ELSE '80+'
END
ORDER BY AVERAGE_EXAM_SCORE DESC

SELECT * FROM EXAM 

---QUESTION 3: HOW DOES PARENTAL INVOLVEMENT IMPACT AVERAGE EXAM SCORES?

SELECT PARENTAL_INVOLVEMENT, ROUND(AVG(EXAM_SCORE),1) AS AVERAGE_EXAM_SCORE 
FROM EXAM 
GROUP BY PARENTAL_INVOLVEMENT
ORDER BY AVERAGE_EXAM_SCORE DESC 



--- QUESTION 4: WHO ARE THE TOP 10 STUDENTS WHO IMPROVED THE MOST 

SELECT TOP 10 STUDENT_ID, PREVIOUS_SCORES, EXAM_SCORE,
ROUND(((EXAM_SCORE - PREVIOUS_SCORES)/Previous_Scores)*100,1)
AS CHANGE_PERCENTAGE
FROM EXAM 
WHERE PREVIOUS_SCORES <> 0 
ORDER BY CHANGE_PERCENTAGE DESC 

--- QUESTION 5: WHO ARE THE TOP 10 STUDENTS WHO DROPPED THE MOST?

SELECT TOP 20 STUDENT_ID, PREVIOUS_SCORES, EXAM_SCORE,
ROUND(((EXAM_SCORE - PREVIOUS_SCORES)/Previous_Scores)*100,1)
AS CHANGE_PERCENTAGE
FROM EXAM 
WHERE PREVIOUS_SCORES <> 0 
ORDER BY CHANGE_PERCENTAGE ASC 


--- QUESTION 6: WHAT IS THE GENDER DISTRIBUTION OF STUDENTS WHO SCORED ABOVE THE AVERAGE EXAM SCORE?

SELECT * FROM EXAM 

SELECT GENDER, COUNT(*) AS NUMBER_OF_STUDENTS
FROM EXAM 
WHERE EXAM_SCORE > (SELECT ROUND(AVG(EXAM_SCORE),1) FROM EXAM )
GROUP BY GENDER 


--- QUESTION 7: WHAT IS THE AVERAGE EXAM SCORE FOR STUDENTS WITH AND WITHOUT ACCESS TO RESOURCES?

SELECT ACCESS_TO_RESOURCES, ROUND(AVG(EXAM_SCORE),1) AS AVERAGE_SCORE
FROM EXAM 
GROUP BY Access_to_Resources
ORDER BY AVERAGE_SCORE DESC

SELECT * FROM EXAM 